"use client";

import { ManagedImage } from "@/components/managed-image";

import { AnimatePresence, motion } from "framer-motion";
import { Award, BookOpen, CheckCircle2, ChevronDown, GraduationCap, ShieldCheck, Sparkles, Users } from "lucide-react";
import { useState } from "react";

const courses = [
  { id: "henne", title: "Art du Henné Royal & Tracés de Précision", subtitle: "Du geste fondamental aux motifs complexes", duration: "3 jours intensifs", schedule: "Dates communiquées sur WhatsApp", description: "Apprenez à préparer le henné naturel, manier le cône et construire des compositions traditionnelles ou modernes avec régularité.", program: ["Préparation du henné naturel", "Tenue du cône et pression", "Motifs géométriques et floraux", "Finition et pratique sur modèle"], target: "Débutantes et professionnelles en perfectionnement", image: "https://images.pexels.com/photos/35148022/pexels-photo-35148022.jpeg?auto=compress&dpr=1&h=900&w=1200", badge: "Signature" },
  { id: "tresses", title: "Expertise Nattes, Laïfou & Napi", subtitle: "Coiffures protectrices et tracés précis", duration: "1 semaine", schedule: "Dates communiquées sur WhatsApp", description: "Maîtrisez le sectionnement, les nattes collées et les coiffures protectrices avec une attention particulière portée au confort et aux finitions.", program: ["Analyse et sectionnement", "Techniques de nattes, Laïfou et Napi", "Gestion de la tension", "Finitions et pratique sur modèle"], target: "Débutantes et coiffeuses en perfectionnement", image: "https://images.pexels.com/photos/36441633/pexels-photo-36441633.jpeg?auto=compress&dpr=1&h=900&w=1200", badge: "Incontournable" },
  { id: "locks", title: "Installation & Resserrage de Micro Locks", subtitle: "Grille, départ et entretien de précision", duration: "Selon la session", schedule: "Dates communiquées sur WhatsApp", description: "Une formation consacrée au diagnostic, au départ de Micro Locks, à la construction d’une grille régulière et aux gestes d’entretien.", program: ["Diagnostic et préparation", "Départ de Micro Locks", "Traçage régulier à la grille", "Resserrage et entretien"], target: "Coiffeuses souhaitant se spécialiser", image: "/images/coiffures/locks/reina-installation-locks-tiktok.webp", badge: "Haute précision" },
  { id: "maquillage", title: "Maquillage Événementiel & Teint Parfait", subtitle: "Mise en beauté professionnelle", duration: "1 semaine", schedule: "Dates communiquées sur WhatsApp", description: "Apprenez à sublimer les peaux noires et métissées avec un teint harmonieux, un regard travaillé et une finition adaptée aux cérémonies.", program: ["Préparation de la peau", "Colorimétrie et choix des teintes", "Contour doux et travail du regard", "Hygiène et tenue du maquillage"], target: "Débutantes et futures professionnelles", image: "https://images.pexels.com/photos/6953621/pexels-photo-6953621.jpeg?auto=compress&dpr=1&h=900&w=1200", badge: "Savoir-faire" },
] as const;

const faqs = [
  ["Le matériel est-il fourni pendant la formation ?", "Le matériel nécessaire aux exercices réalisés sur place est mis à disposition. La liste du matériel personnel conseillé est communiquée avant la session."],
  ["Faut-il déjà avoir de l’expérience ?", "Non. Les modules sont adaptés au niveau des participantes, de l’initiation au perfectionnement."],
  ["Une attestation est-elle remise ?", "Une attestation de participation Reina Beauty est remise aux participantes ayant suivi le module et les exercices prévus."],
  ["Comment réserver une place ?", "Contactez l’équipe via WhatsApp. Les dates, disponibilités et modalités d’inscription vous seront communiquées directement."],
] as const;

export default function AcademyPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  return <main className="min-h-screen bg-luxury-bg pb-20">
    <section className="relative isolate overflow-hidden border-b border-[#ead9dc] bg-[linear-gradient(135deg,#fffaf8_0%,#f8ecee_48%,#f2e3e6_100%)] px-5 py-20 text-center lg:px-8 lg:py-24">
      <div aria-hidden="true" className="absolute -left-24 top-8 -z-10 size-72 rounded-full bg-white/70 blur-3xl" />
      <div aria-hidden="true" className="absolute -right-20 bottom-0 -z-10 size-80 rounded-full bg-[#e7cdd1]/45 blur-3xl" />
      <span className="inline-flex items-center gap-2 rounded-full border border-[#dcc3c8] bg-white/65 px-4 py-2 text-[10px] font-bold uppercase tracking-[.16em] text-luxury-wine shadow-sm backdrop-blur"><GraduationCap className="size-4" /> Académie Reina Beauty</span>
      <h1 className="mx-auto mt-6 max-w-4xl font-serif text-4xl font-bold leading-tight text-[#4b2029] sm:text-6xl">Développez votre savoir-faire dans les arts de la beauté</h1>
      <p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-[#765f64]">Des formations pratiques en henné, nattes, Micro Locks et maquillage, conçues pour acquérir des gestes précis et progresser avec confiance.</p>
      <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="#programmes" className="rounded-full bg-[#6f2636] px-7 py-3 text-[10px] font-bold uppercase tracking-wider text-white shadow-[0_10px_30px_rgba(87,32,44,.16)] transition hover:bg-[#5d202e]">Découvrir les programmes</a><a href="https://wa.me/22371989895?text=Bonjour%20Reina%20Beauty,%20je%20souhaite%20recevoir%20les%20informations%20sur%20vos%20formations." target="_blank" rel="noreferrer" className="rounded-full border border-[#cdaeb5] bg-white/45 px-7 py-3 text-[10px] font-bold uppercase tracking-wider text-[#612633] backdrop-blur transition hover:bg-white/75">Demander les informations</a></div>
    </section>
    <section className="mx-auto -mt-8 max-w-6xl px-5 lg:px-8"><div className="grid gap-5 rounded-3xl border border-luxury-line bg-white p-7 text-center shadow-xl sm:grid-cols-2 lg:grid-cols-4"><Promise icon={Users} title="Petits groupes">Un suivi personnalisé pour progresser.</Promise><Promise icon={Sparkles} title="Pratique réelle">Exercices et mises en situation.</Promise><Promise icon={Award} title="Attestation">Remise à la fin du module suivi.</Promise><Promise icon={ShieldCheck} title="Accompagnement">Conseils pour structurer son activité.</Promise></div></section>
    <section id="programmes" className="mx-auto max-w-7xl space-y-10 px-5 pt-16 lg:px-8"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-luxury-pink">Nos programmes</p><h2 className="mt-2 font-serif text-4xl font-bold">Choisissez votre spécialité</h2></div>{courses.map((course, index) => <motion.article initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} key={course.id} className="grid overflow-hidden rounded-3xl border border-luxury-line bg-white shadow-sm lg:grid-cols-12">
      <div className={`relative min-h-72 lg:col-span-5 ${index % 2 ? "lg:order-2" : ""}`}><ManagedImage src={course.image} alt={course.title} className="absolute inset-0 h-full w-full object-cover" /></div>
      <div className="p-8 sm:p-10 lg:col-span-7"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full bg-luxury-wine px-3 py-1 text-[9px] font-bold uppercase tracking-wider text-white">{course.badge}</span><span className="text-[10px] font-bold uppercase text-luxury-muted">{course.duration}</span></div><h2 className="mt-5 font-serif text-3xl font-bold">{course.title}</h2><p className="mt-1 text-xs font-semibold text-luxury-pink">{course.subtitle}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-luxury-wine">{course.schedule}</p><p className="mt-4 text-xs leading-6 text-luxury-muted">{course.description}</p><div className="mt-6 rounded-2xl bg-luxury-bg p-5"><p className="mb-3 text-[9px] font-bold uppercase tracking-[.18em] text-luxury-wine">Programme du module</p><div className="grid gap-2 sm:grid-cols-2">{course.program.map((item) => <p key={item} className="flex items-start gap-2 text-xs text-luxury-muted"><CheckCircle2 className="mt-0.5 size-3.5 shrink-0 text-luxury-wine" />{item}</p>)}</div></div><p className="mt-6 text-xs"><strong>Pour qui :</strong> {course.target}</p><a href={`https://wa.me/22371989895?text=${encodeURIComponent(`Bonjour Reina Beauty, je souhaite m’inscrire à la formation : ${course.title}.`)}`} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-luxury-wine px-6 py-3 text-[10px] font-bold uppercase text-white"><BookOpen className="size-4" /> S’inscrire via WhatsApp</a></div>
    </motion.article>)}</section>
    <section className="mt-16 border-y border-luxury-line bg-white px-5 py-16 lg:px-8"><div className="mx-auto max-w-7xl text-center"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-luxury-pink">Notre pédagogie</p><h2 className="mt-2 font-serif text-4xl font-bold">Le chemin de l’excellence</h2><div className="mt-10 grid gap-5 md:grid-cols-4">{[["01", "Comprendre", "Hygiène, produits, textures et bases théoriques."], ["02", "Maîtriser le geste", "Entraînement guidé sur supports adaptés."], ["03", "Mettre en pratique", "Réalisation accompagnée et corrections personnalisées."], ["04", "Valider ses acquis", "Évaluation pratique, attestation et conseils de progression."]].map(([step, title, text]) => <div key={step} className="rounded-3xl border border-luxury-line bg-luxury-bg p-7 text-left"><p className="font-serif text-3xl font-bold text-luxury-pink">{step}</p><h3 className="mt-3 font-serif text-xl font-bold text-luxury-wine">{title}</h3><p className="mt-2 text-xs leading-6 text-luxury-muted">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-5 pt-16 lg:px-8"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-luxury-pink">Informations pratiques</p><h2 className="mt-2 font-serif text-3xl font-bold">Questions fréquentes</h2></div><div className="mt-8 space-y-3">{faqs.map(([question, answer], index) => <div key={question} className="overflow-hidden rounded-2xl border border-luxury-line bg-white"><button type="button" onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index} className="flex w-full items-center justify-between gap-4 p-6 text-left font-serif text-base font-bold"><span>{question}</span><ChevronDown className={`size-5 shrink-0 text-luxury-wine transition ${openFaq === index ? "rotate-180" : ""}`} /></button><AnimatePresence initial={false}>{openFaq === index && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }}><p className="border-t border-luxury-line px-6 py-5 text-xs leading-6 text-luxury-muted">{answer}</p></motion.div>}</AnimatePresence></div>)}</div></section>
  </main>;
}

function Promise({ icon: Icon, title, children }: { icon: typeof Users; title: string; children: React.ReactNode }) { return <div className="p-3"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-luxury-bg text-luxury-wine"><Icon className="size-5" /></div><h2 className="mt-3 font-serif text-lg font-bold">{title}</h2><p className="mt-1 text-xs text-luxury-muted">{children}</p></div>; }
