-- Reina Beauty - schéma Supabase
-- À exécuter une seule fois dans Supabase > SQL Editor.

create table if not exists public.catalog_products (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  description text not null,
  price text not null default '',
  image_url text not null default '',
  badge text not null default 'Nouveau',
  published boolean not null default false,
  created_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);
create index if not exists catalog_products_published_idx on public.catalog_products(published);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  subject text not null,
  message text not null,
  status text not null default 'unread' check (status in ('unread','read')),
  created_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);
create index if not exists contact_messages_created_at_idx on public.contact_messages(created_at desc);

create table if not exists public.site_settings (
  key text primary key,
  value text not null,
  updated_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.site_media (
  path text primary key,
  url text not null,
  updated_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);


-- Permissions Data API. Les politiques RLS restent la barrière pour la clé publique.
grant select on public.catalog_products to anon;
grant insert on public.contact_messages to anon;
grant select on public.site_settings to anon;
grant select on public.site_media to anon;
grant all on public.catalog_products, public.contact_messages, public.site_settings, public.site_media to service_role;
grant usage, select on all sequences in schema public to anon, service_role;

alter table public.catalog_products enable row level security;
alter table public.contact_messages enable row level security;
alter table public.site_settings enable row level security;
alter table public.site_media enable row level security;

-- Lecture publique uniquement pour le contenu publié et les réglages nécessaires au site.
drop policy if exists "public read published products" on public.catalog_products;
create policy "public read published products" on public.catalog_products for select to anon using (published = true);

drop policy if exists "public insert contact messages" on public.contact_messages;
create policy "public insert contact messages" on public.contact_messages for insert to anon with check (true);

drop policy if exists "public read site settings" on public.site_settings;
create policy "public read site settings" on public.site_settings for select to anon using (true);

drop policy if exists "public read site media" on public.site_media;
create policy "public read site media" on public.site_media for select to anon using (true);

-- Bucket public pour les images optimisées envoyées depuis l'admin.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('reina-media', 'reina-media', true, 4194304, array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
