"use client";
import { ImagePlus, LoaderCircle, PackagePlus, Pencil, Save, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import type { CatalogProduct } from "@/lib/catalog-products";
import { optimizeImageFile } from "@/lib/client-image";

const empty = { title:"", category:"Soins capillaires", description:"", price:"", imageUrl:"", badge:"Nouveau", published:false };

export function AdminProducts() {
  const [products,setProducts]=useState<CatalogProduct[]>([]), [form,setForm]=useState(empty);
  const [editing,setEditing]=useState<number|null>(null), [saving,setSaving]=useState(false), [image,setImage]=useState<File|null>(null);
  const [creatingCategory,setCreatingCategory]=useState(false);
  const [error,setError]=useState("");
  const load=()=>fetch("/api/admin/products").then(r=>r.json()).then((d:{products?:CatalogProduct[]})=>setProducts(d.products??[]));
  useEffect(()=>{load()},[]);
  const categories=Array.from(new Set(["Soins capillaires","Huiles & sérums","Baumes","Accessoires","Beauté",...products.map(p=>p.category)]));

  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{let imageUrl=form.imageUrl;if(image){const optimized=await optimizeImageFile(image);const fd=new FormData();fd.append("image",optimized);fd.append("scope","products");const up=await fetch("/api/admin/uploads",{method:"POST",body:fd});const data=await up.json() as {url?:string;error?:string};if(!up.ok||!data.url)throw new Error(data.error||"Impossible d’envoyer l’image.");imageUrl=data.url}const res=await fetch(editing?`/api/admin/products/${editing}`:"/api/admin/products",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,imageUrl})});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||"Impossible d’enregistrer le produit.");setForm(empty);setImage(null);setEditing(null);setCreatingCategory(false);load()}catch(reason){setError(reason instanceof Error?reason.message:"Une erreur est survenue.")}finally{setSaving(false)}}
  function edit(p:CatalogProduct){setEditing(p.id);setImage(null);setCreatingCategory(false);setForm({title:p.title,category:p.category,description:p.description,price:p.price,imageUrl:p.image_url,badge:p.badge,published:Boolean(p.published)});document.querySelector("#produits")?.scrollIntoView({behavior:"smooth"})}
  async function remove(id:number){if(!confirm("Supprimer ce produit ?"))return;await fetch(`/api/admin/products/${id}`,{method:"DELETE"});load()}

  return <div className="mt-10 grid gap-8 lg:grid-cols-[.85fr_1.15fr]">
    <form onSubmit={submit} className="h-fit rounded-[2rem] border border-[#ead9dc] bg-white p-7 shadow-sm sm:p-8">
      <div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[#f8ecee] text-[#6f2636]"><PackagePlus className="size-5"/></div><div><h3 className="font-serif text-2xl font-bold text-[#4b2029]">{editing?"Modifier le produit":"Ajouter un produit"}</h3><p className="text-xs text-[#8b7378]">Informations et image enregistrées durablement.</p></div></div>
      {error&&<p className="mt-5 rounded-2xl bg-red-50 px-4 py-3 text-xs font-semibold text-red-700">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-2">
        <Field label="Nom du produit *"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field>
        <label className="text-xs font-semibold text-[#4b2029]">Catégorie *<select value={creatingCategory?"__new__":form.category} onChange={e=>{if(e.target.value==="__new__"){setCreatingCategory(true);setForm({...form,category:""})}else{setCreatingCategory(false);setForm({...form,category:e.target.value})}}} className="mt-2 w-full rounded-2xl border border-[#ead9dc] bg-[#fff9fa] px-4 py-3 font-normal"><option value="" disabled>Choisir une catégorie</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}<option value="__new__">＋ Ajouter une nouvelle catégorie</option></select>{creatingCategory&&<input autoFocus required value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Nom de la nouvelle catégorie" className="mt-3 w-full rounded-2xl border border-[#cdaeb5] bg-white px-4 py-3 font-normal outline-none focus:border-[#6f2636]"/>}</label>
        <Field label="Prix"><input value={form.price} onChange={e=>setForm({...form,price:e.target.value})} placeholder="Ex. 10 000 FCFA"/></Field>
        <Field label="Badge"><input value={form.badge} onChange={e=>setForm({...form,badge:e.target.value})}/></Field>
        <label className="text-xs font-semibold text-[#4b2029] sm:col-span-2">Image du produit<div className="mt-2 rounded-2xl border border-dashed border-[#d9bcc2] bg-[#fff9fa] p-4"><label className="flex cursor-pointer items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#f3dfe3] text-[#6f2636]"><ImagePlus className="size-5"/></span><span><strong className="block text-xs">Choisir une image locale</strong><span className="text-[10px] font-normal text-[#8b7378]">JPG, PNG, WebP ou AVIF — optimisée automatiquement en WebP</span></span><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>setImage(e.target.files?.[0]??null)}/></label>{(image||form.imageUrl)&&<div className="mt-4 flex items-center gap-3"><img src={image?URL.createObjectURL(image):form.imageUrl} alt="Aperçu" className="size-20 rounded-xl object-cover"/><span className="text-xs text-[#766267]">{image?.name||"Image actuelle"}</span></div>}</div></label>
        <Field label="Description *" wide><textarea required minLength={10} rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field>
        <label className="flex items-center gap-3 text-xs font-semibold sm:col-span-2"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})} className="size-4 accent-[#6f2636]"/> Publier sur le catalogue</label>
      </div>
      <div className="mt-6 flex gap-3"><button disabled={saving} className="inline-flex items-center gap-2 rounded-full bg-[#6f2636] px-6 py-3 text-[10px] font-bold uppercase text-white">{saving?<LoaderCircle className="size-4 animate-spin"/>:<Save className="size-4"/>}{editing?"Enregistrer":"Ajouter"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty);setImage(null);setCreatingCategory(false)}} className="rounded-full border border-[#d8b9c0] px-5 py-3 text-[10px] font-bold uppercase text-[#6f2636]">Annuler</button>}</div>
    </form>
    <section><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#a14d60]">Catalogue</p><h3 className="font-serif text-3xl font-bold text-[#4b2029]">Produits enregistrés</h3></div><span className="rounded-full bg-[#f3dfe3] px-3 py-1 text-xs font-bold text-[#6f2636]">{products.length}</span></div><div className="mt-5 space-y-4">{products.map(p=><article key={p.id} className="flex gap-4 rounded-3xl border border-[#ead9dc] bg-white p-5 shadow-sm">{p.image_url?<img src={p.image_url} alt="" className="size-24 rounded-2xl object-cover"/>:<div className="grid size-24 place-items-center rounded-2xl bg-[#f8ecee]"><PackagePlus/></div>}<div className="min-w-0 flex-1"><span className="rounded-full bg-[#f8ecee] px-2.5 py-1 text-[8px] font-bold uppercase text-[#6f2636]">{p.category}</span><h4 className="mt-2 font-serif text-xl font-bold">{p.title}</h4><p className="line-clamp-2 text-xs text-[#766267]">{p.description}</p></div><div className="flex flex-col gap-2"><button onClick={()=>edit(p)} className="grid size-9 place-items-center rounded-full bg-[#f8ecee]"><Pencil className="size-4"/></button><button onClick={()=>remove(p.id)} className="grid size-9 place-items-center rounded-full bg-red-50 text-red-700"><Trash2 className="size-4"/></button></div></article>)}{!products.length&&<div className="rounded-3xl border border-dashed p-12 text-center text-sm text-[#8b7378]">Aucun produit.</div>}</div></section>
  </div>;
}

function Field({label,wide=false,children}:{label:string;wide?:boolean;children:React.ReactElement}){return <label className={`text-xs font-semibold text-[#4b2029] ${wide?"sm:col-span-2":""}`}>{label}<span className="mt-2 block [&>input]:w-full [&>input]:rounded-2xl [&>input]:border [&>input]:border-[#ead9dc] [&>input]:bg-[#fff9fa] [&>input]:px-4 [&>input]:py-3 [&>textarea]:w-full [&>textarea]:rounded-2xl [&>textarea]:border [&>textarea]:border-[#ead9dc] [&>textarea]:bg-[#fff9fa] [&>textarea]:px-4 [&>textarea]:py-3">{children}</span></label>}
