"use client";

import { AnimatePresence, motion } from "framer-motion";
import { Calculator, ChevronDown, Droplets, Leaf, ShieldCheck, ShoppingBag, Sparkles, Star } from "lucide-react";
import { useEffect, useState } from "react";

const initialProducts = [
  { id: "visage-miel", category: "visage", title: "Soin du visage au miel et aux poudres", subtitle: "Nettoyage, douceur et éclat", description: "Un rituel botanique réservé au visage, réalisé selon les besoins de votre peau pour retirer les impuretés et raviver l’éclat du teint.", ingredients: ["Miel", "Poudres botaniques", "Application douce", "Diagnostic peau"], volume: "Prestation au salon", price: "", usage: "Un échange avec notre équipe permet d’adapter le protocole à votre peau. Réservez votre rendez-vous sur WhatsApp.", badge: "Soin visage", action: "Réserver", image: "/images/soins/visage/reina-soin-visage-tiktok.webp" },
  { id: "huile-capillaire", category: "huiles", title: "Huile capillaire nourrissante", subtitle: "Souplesse et nutrition des longueurs", description: "Une huile capillaire conçue pour accompagner la routine des cheveux crépus, frisés, bouclés, tressés ou lockés, sans alourdir les longueurs.", ingredients: ["Application légère", "Longueurs", "Pointes", "Tous types de cheveux"], volume: "Format disponible au salon", price: "", usage: "Appliquer une petite quantité sur les longueurs et les pointes. Demandez à l’équipe la fréquence adaptée à vos cheveux.", badge: "Nutrition", action: "Commander", image: "/images/produits/huile-capillaire/reina-huile-capillaire.webp" },
  { id: "serum-pousse", category: "huiles", title: "Sérum Secret Pousse", subtitle: "Application ciblée du cuir chevelu", description: "Un sérum en flacon compte-gouttes pour compléter le massage du cuir chevelu et prendre soin des tempes, contours et zones fragilisées.", ingredients: ["Compte-gouttes", "Massage ciblé", "Cuir chevelu", "Routine pousse"], volume: "Format disponible au salon", price: "", usage: "Déposer quelques gouttes sur les zones ciblées, puis masser délicatement. Utiliser selon les conseils de Reina Beauty.", badge: "Rituel pousse", action: "Commander", image: "/images/produits/serum-pousse/reina-serum-pousse.webp" },
  { id: "baume", category: "baumes", title: "Baume nourrissant Reina Beauty", subtitle: "Nutrition, souplesse et protection", description: "Une texture riche pensée pour nourrir tous les types de cheveux et préserver la souplesse des longueurs entre deux coiffages.", ingredients: ["Texture riche", "Longueurs", "Pointes", "Tous types de cheveux"], volume: "Format disponible au salon", price: "", usage: "Chauffer une petite noisette entre les paumes, puis appliquer avec légèreté sur les longueurs et les pointes.", badge: "Tous types de cheveux", image: "/images/produits/baume-capillaire/reina-baume-capillaire.webp", action: "Commander" },
  { id: "dermaroller", category: "accessoires", title: "Rouleau de soin du cuir chevelu", subtitle: "Accessoire d’application ciblée", description: "Un accessoire destiné à compléter certaines routines du cuir chevelu, uniquement après conseil personnalisé sur son utilisation et son entretien.", ingredients: ["Usage personnel", "Hygiène stricte", "Conseil préalable", "Application ciblée"], volume: "Accessoire", price: "", usage: "Demandez impérativement conseil à l’équipe avant utilisation. Ne partagez pas l’accessoire et désinfectez-le selon les indications fournies.", badge: "Accessoire", action: "Commander", image: "/images/produits/dermaroller/reina-dermaroller.webp" },
  { id: "manucure", category: "onglerie", title: "Manucure soin complet", subtitle: "Beauté et confort des mains", description: "Un soin complet pour nettoyer, adoucir et embellir les mains et les ongles dans une atmosphère calme et féminine.", ingredients: ["Bain des mains", "Soin des cuticules", "Mise en forme", "Pose soignée"], volume: "Sur rendez-vous", price: "", usage: "La prestation est adaptée à l’état de vos ongles et à la finition souhaitée. Réservez votre créneau sur WhatsApp.", badge: "Soin des mains", image: "https://images.pexels.com/photos/3997379/pexels-photo-3997379.jpeg?auto=compress&dpr=1&h=900&w=1200", action: "Réserver" },
  { id: "pedicure", category: "onglerie", title: "Pédicure soin spa", subtitle: "Détente et beauté des pieds", description: "Un rituel confortable comprenant le soin des ongles et des cuticules, un gommage doux et une finition soignée.", ingredients: ["Bain des pieds", "Gommage doux", "Soin des cuticules", "Massage relaxant"], volume: "Sur rendez-vous", price: "", usage: "Prévoyez un moment de détente dans notre espace exclusivement réservé aux femmes. Réservation conseillée.", badge: "Soin des pieds", image: "https://images.pexels.com/photos/34930135/pexels-photo-34930135/free-photo-of-professional-pedicure-session-at-beauty-salon.jpeg?auto=compress&dpr=1&h=900&w=1200", action: "Réserver" },
] as const;

const filters = [["all", "Tous les soins"], ["visage", "Soin du visage"], ["huiles", "Huiles & sérums"], ["baumes", "Baumes"], ["accessoires", "Accessoires"], ["onglerie", "Manucure & pédicure"]] as const;

const faqs = [
  ["Quand peut-on observer une évolution ?", "Chaque chevelure évolue différemment. Une routine régulière permet d’abord de mieux préserver l’hydratation et de limiter la casse ; la pousse naturelle s’apprécie ensuite dans la durée."],
  ["Le baume convient-il à tous les types de cheveux ?", "Oui. Il nourrit les cheveux crépus, frisés, bouclés, défrisés, tressés ou lockés. Utilisez une petite quantité et adaptez l’application aux besoins de vos longueurs et de votre cuir chevelu."],
  ["Quels produits choisir pour une enfant ?", "Pour une enfant ou un cuir chevelu sensible, demandez conseil à notre équipe avant d’utiliser un produit et effectuez toujours un test sur une petite zone."],
  ["Comment commander un produit ou réserver un soin ?", "Utilisez le bouton affiché sur la fiche concernée. Notre équipe confirme ensuite la disponibilité du produit ou le créneau de rendez-vous sur WhatsApp."],
] as const;

export default function ProductsPage() {
  const [products, setProducts] = useState<Array<{ id: string; category: string; title: string; subtitle: string; description: string; ingredients: readonly string[]; volume: string; price: string; usage: string; badge: string; action: string; image: string }>>([...initialProducts]);
  const [category, setCategory] = useState("all");
  const [hairType, setHairType] = useState("crepus");
  const [goal, setGoal] = useState("pousse");
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const filtered = category === "all" ? products : products.filter((product) => product.category === category);
  const duo = goal === "pousse" ? "Sérum Secret Pousse + Huile Capillaire" : "Huile Capillaire + Baume Nourrissant";

  useEffect(() => { fetch("/api/products").then((response) => response.json()).then((data: { products?: Array<{ id:number; title:string; category:string; description:string; price:string; image_url:string; badge:string }> }) => { const added = (data.products ?? []).map((item) => ({ id:`admin-${item.id}`, category:"huiles", title:item.title, subtitle:item.category, description:item.description, ingredients:[item.category], volume:"Disponible au salon", price:item.price, usage:"Contactez Reina Beauty pour connaître les conseils d’utilisation adaptés.", badge:item.badge, action:"Commander", image:item.image_url || "/images/produits/baume-capillaire/reina-baume-capillaire.webp" })); setProducts([...initialProducts, ...added]); }).catch(() => {}); }, []);

  return <main className="min-h-screen bg-luxury-bg pb-24">
    <section className="relative isolate overflow-hidden border-b border-luxury-line px-5 py-20 lg:px-8">
      <img src="/images/soins/baume/reina-baume-preparation-tiktok.webp" alt="Soin botanique naturel Reina Beauty" className="absolute inset-0 -z-20 h-full w-full object-cover" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-white via-white/95 to-white/35" />
      <div className="mx-auto max-w-7xl"><div className="max-w-2xl"><span className="luxury-badge"><Leaf className="size-4" /> Produits & rituels Reina Beauty</span><h1 className="mt-6 font-serif text-5xl font-bold leading-tight text-luxury-deep sm:text-6xl">Gamme pousse & <span className="text-luxury-wine">soins beauté</span></h1><p className="mt-5 max-w-xl text-sm leading-7 text-luxury-muted">Découvrez nos huiles, sérums et baumes pour les cheveux, ainsi que notre soin du visage au miel et aux poudres botaniques.</p></div></div>
    </section>

    <section className="bg-luxury-wine px-5 py-7 text-white"><div className="mx-auto grid max-w-7xl gap-5 text-center text-[10px] font-bold uppercase tracking-wider md:grid-cols-4"><p className="flex items-center justify-center gap-2"><Droplets className="size-5 text-luxury-champagne" /> Huiles & sérums capillaires</p><p className="flex items-center justify-center gap-2"><Leaf className="size-5 text-luxury-champagne" /> Miel & poudres pour le visage</p><p className="flex items-center justify-center gap-2"><ShieldCheck className="size-5 text-luxury-champagne" /> Adapté à tous les types de cheveux</p><p className="flex items-center justify-center gap-2"><Sparkles className="size-5 text-luxury-champagne" /> Conseils personnalisés</p></div></section>

    <section className="mx-auto max-w-7xl px-5 pt-14 lg:px-8"><div className="rounded-3xl border border-luxury-line bg-white p-7 shadow-sm sm:p-10"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-luxury-pink">Méthode salon</p><h2 className="mt-2 font-serif text-3xl font-bold">Le rituel repousse & densité</h2><p className="mt-2 text-xs text-luxury-muted">Une routine régulière en trois gestes complémentaires.</p></div><div className="mt-8 grid gap-5 md:grid-cols-3">{[["01", "Nettoyer", "Clarifier délicatement le cuir chevelu avec un shampoing adapté."], ["02", "Stimuler", "Appliquer le sérum sur les zones ciblées puis masser doucement le cuir chevelu."], ["03", "Nourrir & protéger", "Appliquer l’huile et le baume avec légèreté sur les longueurs et les pointes."]].map(([step, title, text]) => <article key={step} className="rounded-2xl border border-luxury-line bg-luxury-bg p-6"><p className="font-serif text-3xl font-bold text-luxury-wine">{step}</p><h3 className="mt-3 text-sm font-bold">{title}</h3><p className="mt-2 text-xs leading-6 text-luxury-muted">{text}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 pt-16 lg:px-8"><div className="mb-8 text-center"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-luxury-pink">La collection</p><h2 className="mt-2 font-serif text-4xl font-bold">Nos soins et rituels beauté</h2></div><div className="mb-10 flex gap-2 overflow-x-auto pb-2 sm:flex-wrap sm:justify-center">{filters.map(([id, label]) => <button type="button" key={id} onClick={() => setCategory(id)} className={`shrink-0 rounded-full px-5 py-2.5 text-xs font-bold transition ${category === id ? "bg-luxury-wine text-white" : "border border-luxury-line bg-white text-luxury-muted"}`}>{label}</button>)}</div>
      <motion.div layout className="grid gap-8 md:grid-cols-2 lg:grid-cols-3"><AnimatePresence mode="popLayout">{filtered.map((product) => <motion.article layout initial={{ opacity: 0, scale: .95 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .95 }} key={product.id} className="group flex flex-col overflow-hidden rounded-3xl border border-luxury-line bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-64 overflow-hidden"><img src={product.image} alt={product.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><span className="absolute left-4 top-4 rounded-full bg-luxury-wine px-3 py-1 text-[9px] font-bold uppercase tracking-wider text-white">{product.badge}</span></div><div className="flex flex-1 flex-col p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-luxury-muted">{product.volume}</p><h3 className="mt-2 font-serif text-xl font-bold">{product.title}</h3><p className="mt-1 text-xs font-semibold text-luxury-pink">{product.subtitle}</p><p className="mt-4 text-xs leading-6 text-luxury-muted">{product.description}</p><div className="mt-5 flex flex-wrap gap-1.5">{product.ingredients.map((ingredient) => <span key={ingredient} className="rounded-md bg-luxury-bg px-2.5 py-1 text-[10px] text-luxury-wine">{ingredient}</span>)}</div><div className="mt-5 rounded-xl border border-luxury-line bg-luxury-bg p-3 text-[11px] leading-5 text-luxury-muted"><strong className="text-luxury-wine">Conseil :</strong> {product.usage}</div><div className={`mt-auto flex items-center border-t border-luxury-line pt-5 ${product.price ? "justify-between" : "justify-end"}`}>{product.price && <strong className="font-serif text-lg text-luxury-wine">{product.price}</strong>}<a href={`https://wa.me/22371989895?text=${encodeURIComponent(`Bonjour Reina Beauty, je souhaite ${product.action === "Réserver" ? "réserver" : "commander"} : ${product.title}.`)}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-luxury-wine px-4 py-2.5 text-[10px] font-bold uppercase text-white"><ShoppingBag className="size-4" /> {product.action ?? "Commander"}</a></div></div></motion.article>)}</AnimatePresence></motion.div>
    </section>

    <section id="diagnostic" className="mx-auto max-w-5xl scroll-mt-28 px-5 pt-20 lg:px-8"><div className="grid items-center gap-8 rounded-3xl border border-luxury-line bg-white p-8 shadow-xl lg:grid-cols-2 sm:p-12"><div><span className="luxury-badge"><Calculator className="size-4" /> Diagnostic personnalisé</span><h2 className="mt-5 font-serif text-3xl font-bold sm:text-4xl">Quel duo pour vos cheveux ?</h2><p className="mt-4 text-xs leading-6 text-luxury-muted">Indiquez votre type de cheveux et votre priorité. Cette première orientation ne remplace pas le diagnostic personnalisé de nos coiffeuses.</p></div><div className="rounded-2xl border border-luxury-line bg-luxury-bg p-6"><Selector label="Type de cheveux" value={hairType} onChange={setHairType} options={[["crepus", "Crépus"], ["frises", "Frisés"], ["locks", "Micro Locks"]]} /><div className="mt-5"><Selector label="Objectif prioritaire" value={goal} onChange={setGoal} options={[["pousse", "Accompagner la pousse"], ["casse", "Limiter la casse"]]} /></div><div className="mt-6 border-t border-luxury-line pt-5"><p className="text-[9px] font-bold uppercase tracking-wider text-luxury-muted">Duo recommandé</p><p className="mt-1 font-serif text-lg font-bold text-luxury-wine">{duo}</p><a href={`https://wa.me/22371989895?text=${encodeURIComponent(`Bonjour Reina Beauty, mon diagnostic (${hairType}) recommande : ${duo}.`)}`} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-full bg-luxury-wine px-5 py-3 text-[10px] font-bold uppercase text-white">Demander conseil sur WhatsApp</a></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 pt-20 lg:px-8"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-luxury-pink">Rituels appréciés</p><h2 className="mt-2 font-serif text-4xl font-bold">Pourquoi nos clientes les aiment</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3">{[["Soin visage au miel", "Un protocole doux aux poudres botaniques pour nettoyer la peau et raviver l’éclat du teint."], ["Sérum & huiles", "Une application ciblée et légère, adaptée au massage du cuir chevelu et des zones fragilisées."], ["Routine complète", "Des gestes simples et complémentaires pour maintenir les cheveux nourris au fil de la semaine."]].map(([title, text]) => <article key={title} className="rounded-3xl border border-luxury-line bg-white p-7 shadow-sm"><div className="flex gap-1 text-luxury-wine">{Array.from({ length: 5 }).map((_, i) => <Star key={i} className="size-3.5 fill-current" />)}</div><h3 className="mt-5 font-serif text-xl font-bold">{title}</h3><p className="mt-3 text-xs leading-6 text-luxury-muted">{text}</p></article>)}</div></section>

    <section className="mx-auto max-w-4xl px-5 pt-20 lg:px-8"><div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-luxury-pink">Guide d’utilisation</p><h2 className="mt-2 font-serif text-4xl font-bold">Questions fréquentes</h2></div><div className="mt-9 space-y-3">{faqs.map(([question, answer], index) => <article key={question} className="overflow-hidden rounded-2xl border border-luxury-line bg-white"><button type="button" onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index} className="flex w-full items-center justify-between gap-5 p-6 text-left font-serif text-base font-bold"><span>{question}</span><ChevronDown className={`size-5 shrink-0 text-luxury-wine transition ${openFaq === index ? "rotate-180" : ""}`} /></button><AnimatePresence>{openFaq === index && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }}><p className="border-t border-luxury-line px-6 pb-6 pt-4 text-xs leading-6 text-luxury-muted">{answer}</p></motion.div>}</AnimatePresence></article>)}</div></section>
  </main>;
}

function Selector({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly (readonly [string, string])[] }) {
  return <div><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-luxury-muted">{label}</p><div className="flex flex-wrap gap-2">{options.map(([id, text]) => <button type="button" key={id} onClick={() => onChange(id)} className={`rounded-xl border px-4 py-2.5 text-xs font-semibold ${value === id ? "border-luxury-wine bg-luxury-wine text-white" : "border-luxury-line bg-white text-luxury-muted"}`}>{text}</button>)}</div></div>;
}
