export const SITE_IMAGE_SLOTS = [
  ['/images/marque/reina-logo.jpeg', 'Logo Reina Beauty', 'Identité'],
  ['/images/coiffures/locks/reina-installation-locks-tiktok.webp', 'Installation Micro Locks', 'Accueil & prestations'],
  ['/images/henne/reina-henne.png', 'Henné royal', 'Accueil'],
  ['/images/soins/baume/reina-baume-preparation-tiktok.webp', 'Préparation soin botanique', 'Accueil & soins'],
  ['/images/coiffures/locks/reina-microlocks-clean.png', 'Micro Locks naturelles', 'Accueil & comparaison'],
  ['/images/coiffures/locks/reina-microlocks-color-clean.png', 'Micro Locks colorées', 'Accueil & comparaison'],
  ['/images/coiffures/tresses/reina-braids-child-clean.png', 'Tresses sculpturales', 'Accueil'],
  ['/images/coiffures/locks/reina-video-microlocks-poster.jpg', 'Affiche vidéo Micro Locks', 'Accueil'],
  ['/images/equipe/reina-team-contact-hero.webp', 'Équipe Reina Beauty', 'Contact'],
  ['/images/soins/visage/reina-soin-visage-tiktok.webp', 'Soin visage', 'Soins'],
  ['/images/produits/huile-capillaire/reina-huile-capillaire.webp', 'Huile capillaire', 'Boutique soins'],
  ['/images/produits/serum-pousse/reina-serum-pousse.webp', 'Sérum pousse', 'Boutique soins'],
  ['/images/produits/baume-capillaire/reina-baume-capillaire.webp', 'Baume capillaire', 'Boutique soins'],
  ['/images/produits/dermaroller/reina-dermaroller.webp', 'Rouleau cuir chevelu', 'Boutique soins'],
  ['/images/soins/capillaires/reina-bain-huiles.webp', 'Bain d’huiles', 'Prestations'],
  ['/images/soins/capillaires/reina-vapeur-capillaire.webp', 'Vapeur capillaire', 'Prestations'],
  ['/images/soins/capillaires/reina-massage-cuir-chevelu.webp', 'Massage cuir chevelu', 'Prestations'],
  ['/images/coiffures/nattes/reina-nattes-artistiques.webp', 'Nattes artistiques', 'Prestations'],
  ['/images/coiffures/colorations/reina-coloration-bordeaux.webp', 'Coloration bordeaux', 'Prestations'],
  ['/images/coiffures/colorations/reina-coloration-cuivree.webp', 'Coloration cuivrée', 'Prestations'],
  ['/images/coiffures/colorations/reina-coloration-miel-dore.webp', 'Coloration miel doré', 'Prestations'],
  ['/images/henne/reina-henne-tiktok.webp', 'Henné artistique', 'Prestations'],
  ['/images/coiffures/laifou/reina-laifou-tiktok.webp', 'Coiffure Laïfou', 'Prestations'],
  ['/images/coiffures/nappi/reina-nappi-tiktok.webp', 'Coiffure Napi', 'Prestations'],
] as const;

export type SiteImagePath = typeof SITE_IMAGE_SLOTS[number][0];
