import { ManagedImage } from "@/components/managed-image";
import { Clock3, HeartHandshake, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { phone, phoneDisplay, whatsapp } from "@/lib/reina-data";
import { ContactMessageForm } from "@/components/contact-message-form";

export default function ContactPage() {
  return <main className="min-h-screen bg-luxury-bg pb-20">
    <section className="relative isolate min-h-[520px] overflow-hidden border-b border-luxury-line px-5 py-20 text-white lg:flex lg:min-h-[620px] lg:items-center lg:px-8">
      {/* Image authentique issue de la vidéo de l'équipe @reinabeauties. */}
      <ManagedImage src="/images/equipe/reina-team-contact-hero.webp" alt="L’équipe Reina Beauty dans le salon de Bamako" className="absolute inset-0 -z-20 h-full w-full object-cover object-[67%_center] sm:object-center" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-luxury-deep/95 via-luxury-wine/70 to-luxury-deep/10" />
      <div className="mx-auto w-full max-w-7xl">
        <div className="max-w-xl">
          <span className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/10 px-4 py-2 text-[10px] font-bold uppercase tracking-[.18em] backdrop-blur-md"><HeartHandshake className="size-4" /> L’équipe Reina Beauty</span>
          <h1 className="mt-6 font-serif text-5xl font-bold leading-tight sm:text-6xl lg:text-7xl">Contact & Réservations</h1>
          <p className="mt-6 max-w-lg text-sm leading-7 text-white/85 sm:text-base">Une équipe de professionnelles à votre écoute pour vos soins, vos formations et vos rendez-vous beauté à Bamako.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-white px-6 py-3.5 text-xs font-bold uppercase tracking-wider text-luxury-wine shadow-xl"><MessageCircle className="size-4" /> Écrire sur WhatsApp</a><a href={`tel:${phone}`} className="inline-flex items-center justify-center gap-2 rounded-full border border-white/35 bg-white/10 px-6 py-3.5 text-xs font-bold uppercase tracking-wider text-white backdrop-blur-md"><Phone className="size-4" /> {phoneDisplay}</a></div>
        </div>
      </div>
    </section>
    <section className="mx-auto grid max-w-7xl gap-10 px-5 pt-14 lg:grid-cols-12 lg:px-8">
      <div className="space-y-6 lg:col-span-5"><div className="rounded-3xl border border-luxury-line bg-white p-8 shadow-sm"><h2 className="font-serif text-2xl font-bold">Informations pratiques</h2><div className="mt-7 space-y-6"><Info icon={Phone} label="Téléphone & WhatsApp" value={`+223 ${phoneDisplay}`} /><Info icon={Clock3} label="Horaires" value="Tous les jours, 8h30 – 17h30" /><Info icon={ShieldCheck} label="Politique du salon" value="Espace exclusivement réservé aux femmes" /></div></div><div className="rounded-3xl bg-luxury-wine p-8 text-white shadow-xl"><MapPin className="size-7 text-luxury-champagne" /><h2 className="mt-4 font-serif text-xl font-bold">Salon situé à Bamako</h2><p className="mt-3 text-xs leading-6 text-white/80">La localisation exacte et le guidage sont transmis par WhatsApp lors de la confirmation du rendez-vous.</p></div></div>
      <div className="flex flex-col justify-between rounded-3xl border border-luxury-line bg-white p-8 shadow-xl sm:p-12 lg:col-span-7"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-luxury-pink">Réservation directe</p><h2 className="mt-2 font-serif text-3xl font-bold sm:text-4xl">Prendre rendez-vous</h2><p className="mt-3 text-sm leading-7 text-luxury-muted">Choisissez le canal qui vous convient. Pour une coiffure complexe, vous pouvez joindre une photo à votre message WhatsApp.</p><div className="mt-8 space-y-4"><a href={whatsapp} target="_blank" rel="noreferrer" className="booking-link bg-[#25D366] text-white"><MessageCircle className="size-5" /> Réserver sur WhatsApp</a><a href={`tel:${phone}`} className="booking-link bg-luxury-deep text-white"><Phone className="size-5" /> Appeler le {phoneDisplay}</a></div><div className="mt-7 rounded-2xl border border-luxury-line bg-luxury-bg p-6"><h3 className="font-serif text-lg font-bold text-luxury-wine">Bon à savoir avant votre visite</h3><ul className="mt-3 space-y-2 text-xs leading-6 text-luxury-muted"><li>• Arrivez idéalement 5 minutes avant votre rendez-vous.</li><li>• Le salon est exclusivement réservé aux femmes afin de préserver intimité et confort.</li><li>• La localisation exacte vous est envoyée lors de la confirmation sur WhatsApp.</li></ul></div></div><p className="mt-10 border-t border-luxury-line pt-6 text-center text-xs text-luxury-muted">REINA BEAUTY — Bamako, Mali • Accueil exclusivement sur rendez-vous.</p></div>
    </section>
    <section className="mx-auto max-w-7xl px-5 pt-14 lg:px-8"><div className="grid overflow-hidden rounded-[2rem] border border-luxury-line bg-white shadow-xl lg:grid-cols-[.8fr_1.2fr]"><div className="bg-[linear-gradient(145deg,#5d202e,#8d3145)] p-8 text-white sm:p-12"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-white/65">Nous écrire</p><h2 className="mt-3 font-serif text-4xl font-bold">Une question ou un projet beauté ?</h2><p className="mt-5 text-sm leading-7 text-white/75">Envoyez votre demande directement à l’équipe. Votre message sera consulté depuis l’espace privé Reina Beauty.</p><div className="mt-8 rounded-2xl border border-white/15 bg-white/10 p-5 text-xs leading-6 text-white/80">Pour une réponse plus rapide concernant un rendez-vous du jour, privilégiez WhatsApp ou le téléphone.</div></div><div className="p-8 sm:p-12"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-luxury-pink">Formulaire de contact</p><h2 className="mt-2 font-serif text-3xl font-bold text-luxury-deep">Envoyer un message</h2><ContactMessageForm /></div></div></section>
  </main>;
}

function Info({ icon: Icon, label, value }: { icon: typeof Phone; label: string; value: string }) { return <div className="flex items-start gap-4"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-luxury-bg text-luxury-wine"><Icon className="size-5" /></div><div><p className="text-[9px] font-bold uppercase tracking-wider text-luxury-muted">{label}</p><p className="mt-1 font-serif text-base font-bold">{value}</p></div></div>; }
